services:
  postgres:
    container_name: postgres-kanban
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: kanban
    volumes:
      - postgres:/data/postgres
    ports:
      - 8778:5432
    networks:
      - kanban
    restart: unless-stopped
  keycloak:
    container_name: keycloak-kanban
    image: quay.io/keycloak/keycloak:26.2.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - kanban
    command:
      - "start-dev"
networks:
  kanban:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
